name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x" # tests across multiple Deno versions

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test --unstable --coverage=./cov
        
      - name: generate lcov
        run: deno coverage --unstable --lcov ./cov > cov.lcov

      - name: upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          files: cov.lcov
